SPRITES_PATH="game/sprites.odin"
SPRITES=$(find sprites -type f)

for sprite in $SPRITES; do
	echo $sprite
done

echo "// Generated by sprites.sh" > $SPRITES_PATH
echo "// Do NOT edit manually" >> $SPRITES_PATH
echo "" >> $SPRITES_PATH
echo "package game" >> $SPRITES_PATH
echo "" >> $SPRITES_PATH
echo "import rl \"vendor:raylib\"" >> $SPRITES_PATH
echo "" >> $SPRITES_PATH
echo "SpriteType :: enum {" >> $SPRITES_PATH

for sprite in $SPRITES; do
	enum_name=$(echo $sprite | sed -E "s/sprites\/([a-z])(.*)\.png/Sprite_\U\1\E\2/")
	echo "	" $enum_name , >> $SPRITES_PATH
done

echo "}" >> $SPRITES_PATH
echo "" >> $SPRITES_PATH

echo "make_sprites :: proc() -> [SpriteType]Sprite {" >> $SPRITES_PATH
echo "	sprites : [SpriteType]Sprite" >> $SPRITES_PATH
echo "" >> $SPRITES_PATH

for sprite in $SPRITES; do
	enum_name=$(echo $sprite | sed -E "s/sprites\/([a-z])(.*)\.png/Sprite_\U\1\E\2/")
	size=$(magick identify $sprite | sed -E "s/[a-z0-9A-Z/.]* PNG ([0-9]*)x([0-9]*) .*/\1 \2/")
	x=$(echo $size | awk '{print $1}')
	y=$(echo $size | awk '{print $2}')

	echo "	sprites[.$enum_name] = {" >> $SPRITES_PATH
	echo "		width = $x," >> $SPRITES_PATH
	echo "		height = $y," >> $SPRITES_PATH
	echo "		texture = rl.LoadTexture(\"$sprite\")" >> $SPRITES_PATH
	echo "	}" >> $SPRITES_PATH
	echo "" >> $SPRITES_PATH
done

echo "	return sprites" >> $SPRITES_PATH
echo "}" >> $SPRITES_PATH
echo "" >> $SPRITES_PATH
echo "delete_sprites :: proc(sprites : [SpriteType]Sprite) {" >> $SPRITES_PATH

for sprite in $SPRITES; do
	enum_name=$(echo $sprite | sed -E "s/sprites\/([a-z])(.*)\.png/Sprite_\U\1\E\2/")
	echo "	rl.UnloadTexture(sprites[.$enum_name].texture)" >> $SPRITES_PATH
done

echo "}" >> $SPRITES_PATH
